name: Deploy mdbook to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build, Test and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
            - run: mdbook build && mdbook test
            - uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: book
